name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm run build

      - name: Run vitest
        run: pnpm vitest run

      - name: Test
        run: |
          cd test
          pnpm install
          node index.js 